#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityPowerAndLight.Model
{
	
	
	/// <summary>
	/// The service process stage that this entity is in.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum servicestage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Identify = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Research = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolve = 2,
	}
}
#pragma warning restore CS1591
