#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityPowerAndLight.Model
{
	
	
	/// <summary>
	/// Post message type private or direct.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum socialactivity_postmessagetype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PublicMessage = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PrivateMessage = 1,
	}
}
#pragma warning restore CS1591
